name: Combine PRs

on:
  push:
    branches:
      - main

jobs:
  merge-dependabot-prs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Run script to merge PRs
        run: |
          const branchToMergeInto = 'main';

          const pulls = await github.paginate(
            {
              method: 'GET',
              url: '/repos/:owner/:repo/pulls',
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
              head: 'dependabot',
            }
          );

          if (pulls.length === 0) {
            console.log('No open pull requests authored by dependabot.');
          } else {
            console.log(`Found ${pulls.length} open pull request(s) authored by dependabot.`);

            for (const pull of pulls) {
              const prNumber = pull.number;

              try {
                console.log(`Checking status for PR #${prNumber} with sha ${pull.head.sha}`);
                const statusResponse = await github.rest.repos.getCombinedStatusForRef({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  ref: pull.head.sha,
                });

                if (!statusResponse.data) {
                  console.log(`Skipping PR #${prNumber} because status information is not available.`);
                  continue;
                }

                const status = statusResponse.data.state;

                console.log(`Status of PR #${prNumber}: ${status}`);

                if (status === 'success') {
                  console.log(`Merging PR #${prNumber} into ${branchToMergeInto}`);
                  await github.rest.repos.merge({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    base: branchToMergeInto,
                    head: `refs/pull/${prNumber}/head`,
                  });
                  console.log(`PR #${prNumber} merged successfully.`);
                } else {
                  console.log(`Skipping PR #${prNumber} because it does not have a green status.`);
                }
              } catch (error) {
                console.error(`Error processing PR #${prNumber}:`, error.message);
              }
            }
          }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
